<a href="https://colab.research.google.com/github/moonna03/AIpython/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [4]:
ones_2d = np.ones((3, 4))
print(ones_2d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [18]:
arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
print('shape :', arr2d.shape)
print(arr2d[3,3])
print(arr2d[:2, :2])
print(arr2d[-2:, -2:])
print(arr2d[0], arr2d[1])
print(arr2d[:, -2], arr2d[:, -1])

shape : (5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[1 2 3 4 5] [ 6  7  8  9 10]
[ 4  9 14 19 24] [ 5 10 15 20 25]


In [24]:
arr = np.arange(1, 37)
arr3d = arr.reshape(3, 3, 4)
print(arr3d.shape)
print(arr3d.size)
arrch = arr3d.reshape(3, 4, 3)
print(arrch)
arr1d = arr3d.flatten()
print(arr1d)

(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
